### ISSUE TITLE
Instllation error 500

### ISSUE THREAD

**Issue by mmojadad** [sms77io/zammad#2]
Zammad version 3.2
Hello
After browse to sms77.rb when i click on install package, I redirect to the following page with Error 500
https://myzammad.com/api/v1/packages
![zammad](https://user-images.githubusercontent.com/13836821/88345644-a4debc00-cd5b-11ea-917e-0dcb786c2577.gif)

**Comment by matthiez** [comment]
Hi,

are you on PHP 5.x ? That might be the reason.
If that's the case, I can make a custom branch for you that works on PHP 5.x!

**Comment by mmojadad** [comment]
Hi
I i am on PHP 5.4.16
Yes please provide me a custom branch that works on PHP 5.x

Regards

**Comment by matthiez** [comment]
Please forget what I said as this is a package written in Ruby :-)

I will look into the issue. Give me a couple of days.

**Comment by matthiez** [comment]
But u must have been able to install it at some point according to [this issue](https://github.com/sms77io/zammad/issues/2)?
The package has not changed ever since.

**Comment by mmojadad** [comment]
Still I can not install it and i got the error.

**Comment by matthiez** [comment]
You probably need to install Zammad 3.5.x. It works very well with this version I have just tested it.

**Comment by mmojadad** [comment]
Now i am on Zammad 3.6.x. with same result, Redirect to page Error 500

**Comment by matthiez** [comment]
What Ruby version are you using ? I will test it with your version.

**Comment by mmojadad** [comment]
Version 2.6.6
